services:
  - type: web
    name: doc-analyzer
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon

    healthCheckPath: /health
    autoDeploy: yes

    envVars:
      - key: GOOGLE_API_KEY
        fromSecret: true
      - key: GOOGLE_MODEL
        value: gemini-1.5-flash
      - key: AWS_ACCESS_KEY_ID
        fromSecret: true
      - key: AWS_SECRET_ACCESS_KEY
        fromSecret: true
      - key: AWS_REGION
        fromSecret: true
